2020-06-03 10:13:02,701 ERROR: Exception on /shop [GET] [in c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\super\Knowland\app\main\routes.py", line 203, in shop
    return render_template('shop.html', title=_('KnowLand_Shop'))
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\super\Knowland\app\templates\shop.html", line 3, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\super\Knowland\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 11, in block "html"
    {%- endblock metas %}
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 13, in block "body"
    {%- block styles %}
  File "C:\Users\super\Knowland\app\templates\base.html", line 121, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\super\Knowland\app\templates\shop.html", line 31, in block "app_content"
    <a href="{{ url_for('main.shop_4') }}">{{ _('Cкидка 30% на выбранный курс Skillbox') }}</a> {{ ('100 coin') }}
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\ext.py", line 144, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\ext.py", line 156, in gettext
    return rv % variables
  File "c:\users\super\knowland\knowland_start\lib\site-packages\markupsafe\__init__.py", line 102, in __mod__
    return self.__class__(text_type.__mod__(self, arg))
ValueError: unsupported format character '?' (0x43d) at index 11
2020-06-03 10:19:09,637 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:83]
2020-06-03 10:20:09,800 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:83]
2020-06-03 10:20:16,927 ERROR: Exception on /shop [GET] [in c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\super\Knowland\app\main\routes.py", line 203, in shop
    return render_template('shop.html', title=_('KnowLand_Shop'))
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\super\Knowland\app\templates\shop.html", line 3, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\super\Knowland\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 11, in block "html"
    {%- endblock metas %}
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 13, in block "body"
    {%- block styles %}
  File "C:\Users\super\Knowland\app\templates\base.html", line 121, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\super\Knowland\app\templates\shop.html", line 31, in block "app_content"
    <a href="{{ url_for('main.shop_4') }}">{{ _('Cкидка 30% на выбранный курс Skillbox') }}</a> {{ ('100 coin') }}
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\ext.py", line 144, in _gettext_alias
    return __context.call(__context.resolve("gettext"), *args, **kwargs)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\ext.py", line 156, in gettext
    return rv % variables
  File "c:\users\super\knowland\knowland_start\lib\site-packages\markupsafe\__init__.py", line 102, in __mod__
    return self.__class__(text_type.__mod__(self, arg))
ValueError: unsupported format character '?' (0x43d) at index 11
2020-06-03 13:11:11,530 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:83]
