2020-05-18 18:56:15,961 ERROR: Exception on / [GET] [in c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\super\Knowland\app\main\routes.py", line 46, in index
    return render_template('index.html', title=_('Домашняя страница'), form=form,
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\super\Knowland\app\templates\index.html", line 3, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\super\Knowland\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 11, in block "html"
    {%- endblock metas %}
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 12, in block "body"
  File "C:\Users\super\Knowland\app\templates\base.html", line 73, in block "navbar"
    <li><a >{{ _('LAND_COIN') }} : {{ user.land_coin }}</a></li>
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'user' is undefined
2020-05-18 18:58:24,493 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:83]
2020-05-18 18:58:33,337 ERROR: Exception on / [GET] [in c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\super\Knowland\app\main\routes.py", line 46, in index
    return render_template('index.html', title=_('Домашняя страница'), form=form,
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\super\Knowland\app\templates\index.html", line 3, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\super\Knowland\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 11, in block "html"
    {%- endblock metas %}
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 12, in block "body"
  File "C:\Users\super\Knowland\app\templates\base.html", line 73, in block "navbar"
    <li>{{ _('LAND_COIN') }} : {{ user.land_coin }}</li>
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'user' is undefined
2020-05-18 19:00:38,597 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:83]
2020-05-20 13:03:29,132 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:83]
2020-05-27 10:48:42,663 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:83]
