2020-06-04 12:57:32,967 ERROR: Exception on /reclama [GET] [in c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 2126, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a bool.
2020-06-04 12:58:39,490 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:83]
2020-06-04 12:59:08,685 ERROR: Exception on /reclama [GET] [in c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 2096, in make_response
    raise TypeError(
TypeError: The view function did not return a valid response. The function either returned None or ended without a return statement.
2020-06-04 13:03:22,822 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:83]
2020-06-04 13:04:56,912 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:83]
2020-06-04 13:05:06,133 ERROR: Exception on /reclama [GET] [in c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\super\Knowland\app\main\routes.py", line 248, in reclama
    if current_user.land_coin is None:
  File "c:\users\super\knowland\knowland_start\lib\site-packages\werkzeug\local.py", line 347, in __getattr__
    return getattr(self._get_current_object(), name)
AttributeError: 'AnonymousUserMixin' object has no attribute 'land_coin'
2020-06-04 13:06:03,828 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:83]
2020-06-04 13:07:13,141 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:83]
2020-06-04 13:07:27,101 ERROR: Exception on /reclama [GET] [in c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py:1890]
Traceback (most recent call last):
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\super\Knowland\app\main\routes.py", line 255, in reclama
    return render_template('auth/login.html')
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\super\Knowland\app\templates\auth\login.html", line 3, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\super\Knowland\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 3, in block "doc"
    <html{% block html_attribs %}{% endblock html_attribs %}>
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 11, in block "html"
    {%- endblock metas %}
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 13, in block "body"
    {%- block styles %}
  File "C:\Users\super\Knowland\app\templates\base.html", line 121, in block "content"
    {% block app_content %}{% endblock %}
  File "C:\Users\super\Knowland\app\templates\auth\login.html", line 9, in block "app_content"
    {{ wtf.quick_form(form) }}
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\runtime.py", line 679, in _invoke
    rv = self._func(*arguments)
  File "c:\users\super\knowland\knowland_start\lib\site-packages\flask_bootstrap\templates\bootstrap\wtf.html", line 157, in template
    document is interpreted as a reference to the start of that document,
  File "c:\users\super\knowland\knowland_start\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-06-04 13:09:47,231 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:83]
2020-06-05 12:35:55,620 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:83]
2020-06-05 12:39:17,162 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:83]
2020-06-05 12:40:19,291 INFO: Knowland startup [in C:\Users\super\Knowland\app\__init__.py:83]
